# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Deep Inder Mohan
title: Integrated Masters, IIIT Bangalore
email: deepinder.mohan@iiitb.org
# website: www.github.com/sproogen/resume-theme

# Social links
# twitter_username: facespics
github_username:  deep-guy
# dribbble_username: jekyll
facebook_username: deepindermohan.1
# flickr_username: jekyll
instagram_username: that_deep_guy
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Deep Inder Mohan, and I'm a CS student. I'm currently in an Integrated Masters program in IIIT Bangalore, India. My fields of interest include <mark>Machine Learning</mark>, particularly its applications in <mark>Natural Language Processing</mark>, and also <mark>Agent Based Modelling</mark>. Recently, I have also undertaken research projects in the field of <mark>Cryptography</mark>, particularly, <mark>Secure MPC</mark>. For more info, check out my CV [here]({% post_url DeepInder_CV.pdf %}).
# I am most skilled in: <mark>Python</mark> and <mark>E</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my research interests in ML and Cryptography, I am also an avid debator. I have won multiple competitions at the school and college level for debates and extempores, and also am the head of the Debate Society of IIITB. 

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
